import enum


class Measures(enum.Enum):

    # Board
    BORDERSIZE = 30
    BARSIZE = 50

    TRIANGLEWIDTH = 50
    TRIANGLEHEIGHT = 200
    TRIANGLEGAPSIZE = 50

    QUADRANTWIDTH = TRIANGLEWIDTH * 6
    QUADRANTHEIGHT = TRIANGLEHEIGHT * 2 + TRIANGLEGAPSIZE

    BOARDWIDTH = BORDERSIZE + QUADRANTWIDTH + BARSIZE + QUADRANTWIDTH + BORDERSIZE
    BOARDHEIGHT = BORDERSIZE + QUADRANTHEIGHT + BORDERSIZE

    # Dice pane
    DICEWIDTH = 200
    DICEHEIGHT = BOARDHEIGHT

	# Bottom pane
    BOTTOMWIDTH = BOARDWIDTH + DICEWIDTH
    BOTTOMHEIGHT = 150

    # Main window
    WINDOWWIDTH = BOARDWIDTH + DICEWIDTH
    WINDOWHEIGHT = BOARDHEIGHT + BOTTOMHEIGHT

